//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenteFitApp.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ListaEspera
    {
        [Key]
        public int idListaEspera { get; set; }
        public Nullable<int> idActividad { get; set; }
        public Nullable<int> idHorario { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> posicion { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Horario Horario { get; set; }
    }
}
